#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
require RAILS_ROOT + '/config/environment'


if ARGV.empty?
  puts "Syötä käyttäjän tiedot parametrina, esim: ./script/create_user uurainen admin admin123 admin@admin.com Admin 10"
  exit
end

new_customer = Customer.new
new_customer.name = ARGV[0]

if new_customer.save
  puts "Yhdistys (#{ARGV[0]}) lisättiin onnistuneesti"
else
  puts "Yhdistyksen lisäys epäonnistui"
  puts new_user.errors.full_messages
end

new_user = User.new
new_user.login = ARGV[1]
new_user.password = ARGV[2]
new_user.password_confirmation = ARGV[2]
new_user.email = ARGV[3]
new_user.name = ARGV[4]
new_user.user_level = ARGV[5]
new_user.customer_id = new_customer.id



if new_user.save
  puts "Käyttäjä (#{ARGV[1]}) lisättiin onnistuneesti"
else
  puts "Käyttäjän lisäys epäonnistui"
  puts new_user.errors.full_messages
end
